{% set version = '1.0.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-networklite
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/networkLite_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/networkLite/networkLite_{{ version }}.tar.gz
  sha256: a9fb4a46aee3c8667e8707a1a54dab43c7d4218cc686cea1146594042d405f26

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dplyr
    - r-network >=1.18.1
    - r-statnet.common >=4.8.0
    - r-tibble
  run:
    - r-base
    - r-dplyr
    - r-network >=1.18.1
    - r-statnet.common >=4.8.0
    - r-tibble

test:
  commands:
    - $R -e "library('networkLite')"           # [not win]
    - "\"%R%\" -e \"library('networkLite')\""  # [win]

about:
  home: https://github.com/EpiModel/networkLite/
  license: GPL-3.0-only
  summary: An implementation of some of the core 'network' package functionality based on a simplified
    data structure that is faster in many research applications. This package is designed
    for back-end use in the 'statnet' family of packages, including 'EpiModel'. Support
    is provided for binary and weighted, directed and undirected, bipartite and unipartite
    networks; no current support for multigraphs, hypergraphs, or loops.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
